[project]
name = "tbt"
version = "1.0.0"
description = "A basic Python application built by using the Flask tutorial."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"